//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kuretar_Displayer_Searcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kuretar_Displayer_Searcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_default {
            get {
                object obj = ResourceManager.GetObject("background_default", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button2 {
            get {
                object obj = ResourceManager.GetObject("button2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonstd {
            get {
                object obj = ResourceManager.GetObject("buttonstd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonstdClick {
            get {
                object obj = ResourceManager.GetObject("buttonstdClick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonstdMouse {
            get {
                object obj = ResourceManager.GetObject("buttonstdMouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chat_settings_hover_32 {
            get {
                object obj = ResourceManager.GetObject("chat_settings_hover_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 224|0|0|0|0
        ///233|0|0|0|0|typetex:jambes basses;pieds|mail_a_01_boot_ll_f;mail_a_01_boot_fo_f
        ///242|0|0|0|0
        ///245|0|0|0|0
        ///249|0|0|0|0
        ///253|0|0|0|0
        ///257|0|0|0|0
        ///261|0|0|0|0
        ///292|0|0|0|0
        ///295|0|0|0|0
        ///302|0|0|0|0|typetex:jambes basses;pieds|leather_demonhunter_a_01_silver_boot_ll_u;leather_demonhunter_a_01_silver_boot_fo_u
        ///310|0|0|0|0
        ///311|0|0|0|0
        ///362|0|0|0|0
        ///365|0|0|0|0
        ///368|0|0|0|0
        ///369|0|0|0|0
        ///370|0|0|0|0
        ///371|0|0|0|0
        ///372|0|0|0|0
        ///373|0|0|0|0
        ///374|0|0|0|0
        ///383|0|0|0|0
        ///386|0|0|0|0
        ///387|0|0|0|0
        ///392|0|0 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string DB_ITEM_BFA {
            get {
                return ResourceManager.GetString("DB_ITEM_BFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Helm_Logo {
            get {
                object obj = ResourceManager.GetObject("Helm_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 4 | murloc2,
        ///13 | hufmcitizenlow,
        ///16 | humanthief,
        ///17 | humlblacksmith,
        ///18 | humlmagicsmith,
        ///19 | humlmerchant,
        ///31 | murloc2,
        ///33 | ogremage,
        ///62 | hydra,
        ///64 | murloc2,
        ///68 | doomguard2,
        ///69 | elementalearth2,
        ///71 | harvestgol,
        ///73 | direwolf,
        ///80 | humanfemalekid2,
        ///89 | humanmalepeasantwood,
        ///91 | silithidtank,
        ///95 | humanfemalemerchantfat,
        ///96 | humanfemalemerchantthin,
        ///99 | humanfemalewarriorlight,
        ///105 | humanmalewarriormedium,
        ///108 | humanmalecaster,
        ///110 | waterelemental2,
        ///113 | orcmalemerch [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ListingMorph {
            get {
                return ResourceManager.GetString("ListingMorph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logoPlaceholder {
            get {
                object obj = ResourceManager.GetObject("logoPlaceholder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Monster_Logo {
            get {
                object obj = ResourceManager.GetObject("Monster_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Sword_Logo {
            get {
                object obj = ResourceManager.GetObject("Sword_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
